tests env updated (#155)
* tests env updated

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,6 +12,9 @@ before_script:
 
 before_install:
     - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
+    - wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
+    - chmod +x phpunit
+    - mkdir -p build/logs
 
 install:
   - if [[ $deps = 'low' ]]; then
@@ -21,13 +24,12 @@ install:
     fi
 
 script:
-    - ./vendor/bin/phpunit -c phpunit.xml.dist
+    - ./phpunit -c phpunit.xml.dist
 
 jobs:
     allow_failures:
         - php: nightly
     include:
-        - php: '7.2'
         - php: '7.3'
         - php: '7.4'
         - php: '7.4'
@@ -36,17 +38,16 @@ jobs:
         - stage: Metrics and quality
           env: COVERAGE
           before_script:
-              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
-              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
-              - wget https://phar.phpunit.de/phpcov.phar
-              - chmod +x phpcov.phar
+              - wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
+              - chmod +x phpunit
               - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
               - chmod +x php-coveralls.phar
+              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
+              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
           script:
-              - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-php build/cov/coverage.cov
+              - ./phpunit --coverage-clover build/logs/clover.xml
           after_script:
-              - phpcov.phar merge --clover build/logs/clover.xml build/cov
-              - php-coveralls.phar --no-interaction
+              - ./php-coveralls.phar --no-interaction
 
         - stage: Metrics and quality
           env: STATIC_ANALYSIS
